BASE_URL = "https://api.openf1.org/v1"

MEETINGS = "/meetings"
SESSIONS = "/sessions"
DRIVERS = "/drivers"
POSITION = "/position"
LAPS = "/laps"
CAR_DATA = "/car_data"
WEATHER = "/weather"
INTERVALS = "/intervals"
PIT = "/pit"
RACE_CONTROL = "/race_control"
TEAM_RADIO = "/team_radio"
STINTS = "/stints"
LOCATION = "/location"
